server:
  port: 30303

spring:
  profiles:
    active: dev

  cloud:
    gateway:
      routes:
        - id: system-admin-api
          uri: lb://system-server
          predicates:
            - Path=/api-admin/system/**
          filters:
            - RewritePath=/api-admin/system/v3/api-docs, /v3/api-docs
            - RewritePath=/api-admin/system/(?<segment>.*), /$\{segment}
      x-forwarded:
        prefix-enabled: false

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
