server:
  port: 30001

spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档
  group-configs:
    - group: 'default'
      packages-to-scan: ${alive.info.base-package}
knife4j:
  enable: true
  setting:
    language: zh_cn

alive:
  info:
    version: 1.0.0
    base-package: com.careyq.alive.system
  swagger:
    title: ALIVE 管理系统
    description: ALIVE 系统后台管理功能
    version: ${alive.info.version}