server:
  port: 30303

spring:
  application:
    name: alive-server
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 1h
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
  servlet:
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  type-aliases-package: ${alive.info.base-package}.module.*.entity

springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  token-style: random-64
  token-name: Authorization

alive:
  info:
    version: 1.0.0
    base-package: com.careyq.alive
  swagger:
    title: ALIVE 管理系统
    description: ALIVE 系统后台管理功能
    version: ${alive.info.version}
  codegen:
    base-package: ${alive.info.base-package}
    